<?php

/**
 * @file
 * Contains headscape_image_background.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function headscape_image_background_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the headscape_test module.
    case 'help.page.headscape_image_background':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field formatter for adding a background image with custom class(es)') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function headscape_image_background_theme($existing, $type, $theme, $path): array
{
  return [
    'background_image' => [
      'variables' => [
        'wrapper_class' => null,
        'image_url' => null,
      ],
    ],
  ];
}
